### ISSUE TITLE
Create general mailing lists

### ISSUE THREAD

**Issue by JonasHelming** [openETCS/ecosystem#15]
Proposal
All participants
WPs

**Comment by mknauer** [comment]
One remark to this one: Would it make sense to create a minimal (maybe private) Google Apps account and map this to a certain DNS name? I think it would make sense to create all the Google groups below the openetcs.info domain instead of something.google.com

**Comment by JonasHelming** [comment]
how much does it cost?

**Comment by mknauer** [comment]
In theory we could start with an account that comes for free, but maybe we have to enable some feature that need a paid account. In that case we would need at last _one_ account (40-50 Euro p.a.).
