### ISSUE TITLE
Create a page containing all public mailinglists

### ISSUE THREAD

**Issue by JonasHelming** [openETCS/ecosystem#31]

**Comment by MatthiasKuhn** [comment]
Mit freundlichen Grüßen / Kind Regards

Matthias Kuhn
OpenETCS Project
HCZ (INVT3)

DB Netz AG
Völckerstrasse 5, 80939 München
Tel. +49 89 13087789-Intern 9627789

---

Der DB-Konzern im Internet >> http://www.deutschebahn.com

Sitz der Gesellschaft: Frankfurt am Main
Registergericht: Frankfurt am Main, HRB 50879
USt-IdNr.: DE 199861757
Vorstand: Oliver Kraft (Vorsitzender), Dr. Roland Bosch, Hansjörg Hess, Dr.
Jörg Sandvoß, Hans-Otto Umlandt
Vorsitzender des Aufsichtsrates: Dr. Rüdiger Grube

**Comment by JonasHelming** [comment]
should be on this page:
http://openetcs.org/contact/

**Comment by JonasHelming** [comment]
should include a link to this page

**Comment by BerndHekele** [comment]
@Farhangi Hallo Peyman,, das ist noch ein Erbe von Matthias und sollte von uns weitergeführt werden.
Außerdem passt es - glaube ich - in den Umbau der openETCS Seiten. Kannst Du mal reinschauen?
Viele Grüße
Bernd

**Comment by BerndHekele** [comment]
see https://github.com/openETCS/ecosystem/wiki/Mailing-Lists
