### ISSUE TITLE
Contribution Guidelines: Unversioned references to the terms of use and IP policy

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/ecosystem#40]
The contribution guidelines between SNIP and SNAP include the text:

> I hereby declare that I accept to contribute following the openETCS terms of use and the openETCS IP policy. 
> http://openetcs.org/termsofuse/
> https://github.com/openETCS/ecosystem/wiki/IP-Policy

Both hyperlinks do not specify the version of the openETCS terms of use and IP policy and therefore a not sufficient as valid nonambiguous references for contributions. 

In conclusion, the hyperlinks within the contribution guidelines, the terms of use and the IP policy must be equipped with traceable and referenceable version tags.

**Comment by JonasHelming** [comment]
indeed

**Comment by JonasHelming** [comment]
@BerndHekele : can the PO take care of this?

**Comment by BerndHekele** [comment]
@JonasHelming : Is it sufficient for the change control to provide the text-components in some repository of openetcs?

**Comment by JonasHelming** [comment]
@BerndHekele : As the documents are in the wiki (ecosystem project), they are under version control (git repository). The missing piece is a version number, which is visible in the document. It is easy to add one, but that involves the decision, which version to chose. If we consider the ecosystem project as an incibation project, we should start with 0.1. If we consider the ecosystem project as graduated, then we should start with 1.0.

**Comment by BerndHekele** [comment]
@JonasHelming : I get the point. Is the "terms of use" really in Git? Is there a procedure existing to decide on the grade or can we doe this by guts feeling? I would set ecosystem to graduated.

**Comment by JonasHelming** [comment]
@BerndHekele : I think the QA plan should define criteria for graduated projects. If we match these criteria, I think there should be a graduation review.

**Comment by BerndHekele** [comment]
I will add visible version numbers and dates to the mentioned documents.

**Comment by BerndHekele** [comment]
There are some concerns regarding legal options stil open. Howeever, this tool is not the right place to follow them up.
Since the portions related to the infra-structures are solved I will close the issue. Legal constrains will be taken over into PMB.
