### ISSUE TITLE
How to review tex documents on openETCS github repositories 

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/ecosystem#42]
Dear *, 
I’m not sure how to review tex documents on github exactly. 

For the actual review of req_synthesis.tex within the requirements repository I forked the repository into my github account, cloned it to my local PC, changed the review object req_synthesis.tex, committed the changes to my local repository, pushed the changes to my forked repository on github and sent a pull request to the original repository. That all seems to work properly. 

But the procedure within the .tex file is not clear: 
• Do I have to mark my changes, if I want to add text or delete existing text?
• If yes, do I have to make use of special review tags/delimiters for that purpose? 
• If I want to add remarks, has this to be done in form of  block comments or margin notes or … ? 
• Are there review capabilities in the underlying tex template for document reviews ? 

I think, a HowTo for reviews for tex and other documents would help a lot. 

Best regards,
Uwe Steinke

**Comment by srieger** [comment]
For remarks maybe this is a solution: http://www.tex.ac.uk/tex-archive/macros/latex/contrib/todonotes/todonotes.pdf

**Comment by MerlinPokam** [comment]
The document is in great!

**Comment by JonasHelming** [comment]
fixed:
https://github.com/openETCS/ecosystem/wiki/LatexHowto
https://github.com/openETCS/ecosystem/wiki/Howto%20to%20do%20pull%20requests
