### ISSUE TITLE
Committer Vote for David Mentre

### ISSUE THREAD

**Issue by JonasHelming** [openETCS/ecosystem#44]
He has contributed parts of the LaTeX template and is willing to write guidelines how to use it in the future.

**Comment by mknauer** [comment]
+1

**Comment by mgudemann** [comment]
sorry, shouldn't vote as non-committer

**Comment by stanpinteTheSignallingCompany** [comment]
+1

**Comment by KlausRuedigerHase** [comment]
+1

**Comment by JonasHelming** [comment]
voting sucessfully closed with 75% acceptance. Please note that Stans vote does not count, as he is not a committer.
