### ISSUE TITLE
Format Errors on Committer Election HOWTO page

### ISSUE THREAD

**Issue by mgudemann** [openETCS/ecosystem#45]
There are some formatting errors on the following page:
https://github.com/openETCS/ecosystem/wiki/Development-Resources-HOWTO-Nominating-and-Electing-a-New-Committer

for example, it starts with

"Development Resources/HOWTO/Nominating and Electing a New Committer - Eclipsepedia 

Matthias

**Comment by JonasHelming** [comment]
the current documentation can be found here
https://github.com/openETCS/ecosystem/wiki/Committer-Election-Guideline
the page your refer to is very old, it should be removed

**Comment by JonasHelming** [comment]
I have seen that there a recent changes in the document, is this still on-going work? Then I would close this issue...

**Comment by JonasHelming** [comment]
@BerndHekele : Could you please check this with Klaus-Rüdiger? If the page is obsolete, we should delete it...

**Comment by BerndHekele** [comment]
@JonasHelming : I will check. My understanding in this issue: we need soemthing on top of the simple eclipse approach. I also believe the work started by Klaus is not "done" yet and needs some review.
I will take this action to complete the description and get it distributed.

**Comment by JonasHelming** [comment]
@BerndHekele Hav you had the chance to check this?

**Comment by JonasHelming** [comment]
As there was no Feedback, I deleted the page. If we need it again in the future, we can recover it from the history
