### ISSUE TITLE
Delete "Committer Guidelines"?

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/ecosystem#49]
@JonasHelming 
I want to get the documentation on "committer approval" clean. I see the "committer guidelines" as an empty document and propose to delete it. Or did I get the purpose of the document wrong? If thre is need for references we can take the approval guideline as a valid document.

**Comment by JonasHelming** [comment]
+1 for deletion

**Comment by BerndHekele** [comment]
Page deleted.
Issue to be closed
