### ISSUE TITLE
Wrong reference  to project proposal template.

### ISSUE THREAD

**Issue by KlausRuedigerHase** [openETCS/ecosystem#51]
Obviously with the change of policy at GitHub not to allow  not version controlled uploads, that link:
https://github.com/eclipsesource/openECTS-ecosystem/downloads

dose not work any more.

I would suggest to upload that template into the "Template" repository in a version controlled fashion and chang the obove link accordingly.

Jonas, I think that template came from your side.?!

**Comment by JonasHelming** [comment]
Where did you find this link? You are right, that the downloads feature is deprecated. However, the link looks even more wrong as it contains "eclipsesource" and "openETCS-ecosystem"

**Comment by BerndHekele** [comment]
The project proposal template is located here:
https://github.com/openETCS/ecosystem/blob/master/Project-Proposal-Template.md

I have updated the guideline.
