### ISSUE TITLE
packages and styles with Latex

### ISSUE THREAD

**Issue by MariellePetitDoche** [openETCS/ecosystem#55]
Each author of latex files add his own package. this gives troubles if anybody else will modify and check the modifications.

How can we manage to  share information on the package used in each documents ?

Can we create a subdirectory close to the latex template with the used packaged (at least the open source one) or the way to found them ?

**Comment by JonasHelming** [comment]
What exactly do you mean by "package" ?

**Comment by MariellePetitDoche** [comment]
all the specific elements added by a \usepackage{...} command at the beginning of a main latex document.

Some are linked to a specific language, some to draw picture or gantt, some to manage hyperlink, some to manage specific French or German characters,...
And some are sometimes in conflict.

To facilitate exchange, I think we have to be rigorous on how to use them or to share information on them.

**Comment by JonasHelming** [comment]
I see, could you point me to a concrete example, where they are in conflict?

**Comment by JonasHelming** [comment]
Without an concrete example, we cannot fix this...

**Comment by MariellePetitDoche** [comment]
I fixed my specific trouble a time ago, and as noody else complained, we can close the issue.
