### ISSUE TITLE
openETCS logo

### ISSUE THREAD

**Issue by morido** [openETCS/ecosystem#57]
1. Can anybody tell me why there are two different openETCS-logos (namely [1a](https://github.com/openETCS/ecosystem/blob/master/logo.eps) / rsp. [1b](https://github.com/openETCS/ecosystem/blob/master/logo.svg) vs. [2](https://github.com/openETCS/ecosystem/blob/master/openETCS_LateX_templates/beamer_template/openetcs_logosmall.png)?
2. Logo 1 a/b seems not to be used in any of the documents. So what is it good for?
3. Where can I find a vectorized version of logo 2?

**Comment by JonasHelming** [comment]
good question. The first one was created by us, the second one seems to be a word art, so probably there is not vector version. On the web page we originally had the first one, but somebody replaced it recently. I prefer the first one, the second one looks like word art
@BerndHekele

**Comment by JonasHelming** [comment]
Any comments?

**Comment by BerndHekele** [comment]
I would like to assign this to Peter: @mahlmann .
I have not been involved in logos.

**Comment by JonasHelming** [comment]
done.
@mahlmann could you take care about this?

**Comment by mahlmann** [comment]
Well, actually I also prefer the first one. However, the second one seems to be the "official" logo since it is used on the projects webpage as well as in the presentation template. To the best of my knowledge it is indeed word art and has been created by @KlausRuedigerHase . 

Maybe @KlausRuedigerHase can comment why the logo has been changed?

**Comment by jastram** [comment]
I recall that it was decided eventually to stick with the old logo.  Considering that people seemed to like the new logo (and as it was available anyway), I used it (for now) for the toolchain, see http://openetcs.org/tool

Suggestion:
- Old Logo: openETCS project
- New Logo: openETCS tool

**Comment by JonasHelming** [comment]
Peyman changed our intial website proposal back to the word art logo on April 4th. I think it does not make any sense to maintain different logos for the project and the tool.
As Peyman changed it back, probably someone did not like the new one. @DB: Could you clarify this internally?

**Comment by mahlmann** [comment]
I checked back with Klaus-Rüdiger Hase: 2 (word art) is the original and official logo of the project. 

We should think about a change of the logo for a follow up project at best.

**Comment by JonasHelming** [comment]
Can we close this issue then?

**Comment by jastram** [comment]
Before closing the item, I suggest moving logo #1 to a subdirectory, and to document its use in the folder's readme.  @JonasHelming, as you are the originator of the file, can you do this?  Thanks!

**Comment by JonasHelming** [comment]
The use? As I understand the logo is deprecated now...
@Farhangi : As you have introduced the orginal change, please do as you wish.

**Comment by jastram** [comment]
We'll keep using it for the tool (http://openetcs.org/tool/), unless told otherwise.
