### ISSUE TITLE
Committer validation / MERCEmentre

### ISSUE THREAD

**Issue by mahlmann** [openETCS/ecosystem#65]
Dear @MERCEmentre 

you are currently committer of the ecosystem repository. However, you have not been active in this repository for a longer period of time. Please let me know if you expect to commit in the future. If this is not the case you will be removed from the group of committers.

**Comment by MERCEmentre** [comment]
Hello. I don't plan to do a commit in the following days. You can remove me as committer.

**Comment by mahlmann** [comment]
Thanks, David.
